[project]
name = "business-card"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=6.0",
    "django-stubs>=5.2.8",
    "fastapi>=0.128.0",
    "mypy>=1.19.1",
    "pydantic[email]>=2.12.5",
    "uvicorn>=0.40.0",
    "boto3>=1.35.0",
    "mypy-boto3-s3>=1.35.0"
]

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    "ruff>=0.14.11",
]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "I"] # 기본 오류, 미사용 변수, 임포트 정렬
fix = true # 자동 수정 허용
